

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(430, 580)
        mainWindow.setMinimumSize(QtCore.QSize(430, 580))
        mainWindow.setMaximumSize(QtCore.QSize(430, 580))
        mainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(180, 160, 121, 61))
        self.deleteButton.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.deleteButton.setObjectName("deleteButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(330, 160, 75, 61))
        self.plusButton.setStyleSheet("background-color: rgb(47, 255, 175);")
        self.plusButton.setObjectName("plusButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget)
        self.equalButton.setGeometry(QtCore.QRect(330, 440, 75, 91))
        self.equalButton.setStyleSheet("background-color: rgb(255, 146, 74);")
        self.equalButton.setObjectName("equalButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton.setGeometry(QtCore.QRect(330, 230, 75, 61))
        self.minusButton.setStyleSheet("background-color: rgb(47, 255, 175);")
        self.minusButton.setObjectName("minusButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget)
        self.threeButton.setGeometry(QtCore.QRect(230, 240, 75, 61))
        self.threeButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.threeButton.setObjectName("threeButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget)
        self.twoButton.setGeometry(QtCore.QRect(130, 240, 75, 61))
        self.twoButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.twoButton.setObjectName("twoButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget)
        self.oneButton.setGeometry(QtCore.QRect(30, 240, 75, 61))
        self.oneButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.oneButton.setObjectName("oneButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget)
        self.sixButton.setGeometry(QtCore.QRect(230, 320, 75, 61))
        self.sixButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.sixButton.setObjectName("sixButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.fiveButton.setGeometry(QtCore.QRect(130, 320, 75, 61))
        self.fiveButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.fiveButton.setObjectName("fiveButton")
        self.multipliedButton = QtWidgets.QPushButton(self.centralwidget)
        self.multipliedButton.setGeometry(QtCore.QRect(330, 300, 75, 61))
        self.multipliedButton.setStyleSheet("background-color: rgb(47, 255, 175);")
        self.multipliedButton.setObjectName("multipliedButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget)
        self.fourButton.setGeometry(QtCore.QRect(30, 320, 75, 61))
        self.fourButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.fourButton.setObjectName("fourButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sevenButton.setGeometry(QtCore.QRect(30, 400, 75, 61))
        self.sevenButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget)
        self.eightButton.setGeometry(QtCore.QRect(130, 400, 75, 61))
        self.eightButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget)
        self.nineButton.setGeometry(QtCore.QRect(230, 400, 75, 61))
        self.nineButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.nineButton.setObjectName("nineButton")
        self.dividedButton = QtWidgets.QPushButton(self.centralwidget)
        self.dividedButton.setGeometry(QtCore.QRect(330, 370, 75, 61))
        self.dividedButton.setStyleSheet("background-color: rgb(47, 255, 175);")
        self.dividedButton.setObjectName("dividedButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(30, 160, 121, 61))
        self.clearButton.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.clearButton.setObjectName("clearButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.zeroButton.setGeometry(QtCore.QRect(30, 470, 121, 61))
        self.zeroButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.zeroButton.setObjectName("zeroButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget)
        self.dotButton.setGeometry(QtCore.QRect(180, 470, 121, 61))
        self.dotButton.setStyleSheet("background-color: rgb(202, 198, 69);")
        self.dotButton.setObjectName("dotButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 10, 371, 121))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Hesap Makinesi"))
        self.deleteButton.setText(_translate("mainWindow", "Sil"))
        self.plusButton.setText(_translate("mainWindow", "+"))
        self.equalButton.setText(_translate("mainWindow", "="))
        self.minusButton.setText(_translate("mainWindow", "-"))
        self.threeButton.setText(_translate("mainWindow", "3"))
        self.twoButton.setText(_translate("mainWindow", "2"))
        self.oneButton.setText(_translate("mainWindow", "1"))
        self.sixButton.setText(_translate("mainWindow", "6"))
        self.fiveButton.setText(_translate("mainWindow", "5"))
        self.multipliedButton.setText(_translate("mainWindow", "X"))
        self.fourButton.setText(_translate("mainWindow", "4"))
        self.sevenButton.setText(_translate("mainWindow", "7"))
        self.eightButton.setText(_translate("mainWindow", "8"))
        self.nineButton.setText(_translate("mainWindow", "9"))
        self.dividedButton.setText(_translate("mainWindow", "/"))
        self.clearButton.setText(_translate("mainWindow", "Temizle"))
        self.zeroButton.setText(_translate("mainWindow", "0"))
        self.dotButton.setText(_translate("mainWindow", "."))

